version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - cd frontend
      - npm install
      - npm install next -g

  build:
    commands:
      - NODE_ENV=production npm run build

  post_build:
    commands:
      - rm -rf node_modules

artifacts:
  base-directory: frontend
  files:
    - '**/*'
