version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - cd backend
      - npm install && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - rm -rf node_modules

artifacts:
  base-directory: backend
  files:
    - '**/*'
