version: 0.2

phases:
  install:
    commands:
      - n 14.18.3

  pre_build:
    commands:
      - cd apps/backend
      - npm install

  build:
    commands:
      - NODE_ENV=production npm run build

  post_build:
    commands:
      - rm -rf node_modules
      - if [ "$CODEBUILD_INITIATOR" = "codepipeline/landing-page-cms-backend-dev" ]; then rm -rf .ebextensions ; fi

artifacts:
  base-directory: apps/backend
  files:
    - '**/*'
