name: Deploy/Production/Frontend

env:
  BUILD_ARTIFACT: production-frontend-build

on:
  push:
    branches: ["main"]
    paths: ["apps/frontend/**"]

jobs:
  prettier:
    name: Check Format
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        working-directory: ./apps/frontend
        run: yarn check-format

  build-and-test:
    name: Build & Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Create build
        working-directory: ./apps/frontend
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_API_ROUTE: "RCooqUQMNl77xg89tP848X6rETMeCapGNIUyzuz6oZzhOd7SHfPcUi6kYeIcZ52f"

      - name: Test (Unit)
        working-directory: ./apps/frontend
        run: yarn test

      # - name: Test (E2E)
      #   working-directory: ./apps/frontend
      #   run: yarn test:e2e:run

      - name: Generate dist
        working-directory: ./apps/frontend
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: $BUILD_ARTIFACT
          retention-days: 1
          path: ./apps/frontend/deploy.zip

  deploy:
    needs: [prettier, build-and-test]
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: $BUILD_ARTIFACT

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          wait_for_environment_recovery: 120
          application_name: landing-page-cms-frontend
          environment_name: landing-page-cms-frontend-prod-v18
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: deploy.zip
